---
- name: Configure 1:1 NAT Rule on Cisco Firepower
  hosts: all
  gather_facts: no
  vars:
    ansible_connection: network_cli
    ansible_network_os: cisco.asa.asa
    ansible_become: yes
    ansible_become_method: enable
    ansible_become_password: Cisco123
    nat_rule_name: "Static NAT 1:1"
    inside_ip: "192.168.1.100"
    outside_ip: "203.0.113.100"

  tasks:
    - name: Ensure we are logged in to the Firepower device
      ios_command:
        commands: ['show version']
    
    - name: Create 1:1 NAT rule
      asa_config:
        lines:
          - "object network obj-{{ inside_ip }}"
          - "host {{ inside_ip }}"
          - "nat (inside,outside) static {{ outside_ip }}"
        save_when: modified

    - name: Verify NAT rule
      ios_command:
        commands: 
          - "show running-config object network obj-{{ inside_ip }}"
          - "show running-config nat"
      register: nat_output

    - name: Display NAT configuration
      debug:
        var: nat_output.stdout_lines