---
- name: Configurar regra de firewall 1:1 no Cisco Firepower
  hosts: all
  connection: local
  gather_facts: no
  collections:
    - community.network

  tasks:

    - name: Configurar a regra de acesso correspondente
      ftd_configuration:
        operation: "addAccessRule"
        path_params: {}
        query_params: {}
        data:
          name: "{{ nat_rule_name }}"
          action: "allow"
          enabled: true
          sourceZone: "outside"
          destinationZone: "inside"
          sourceNetwork: "any"
          destinationNetwork: "{{ destination_ip }}"
          sourcePort: "{{ source_port }}"
          destinationPort: "{{ destination_port }}"