---
- name: Configurar regra de firewall 1:1 no Cisco Firepower
  hosts: all
  connection: local
  gather_facts: no
  collections:
    - community.network

  tasks:

    - name: Configurar a regra de acesso correspondente
      ftd_configuration:
        operation: "addAccessRule"
        path_params: {}
        query_params: {}
        data:
          name: "{{ nat_rule_name }}"
          action: "allow"
          enabled: true
          sourceZone: "outside_zone"
          destinationZone: "inside_zone"
          sourceNetworks:
            - type: "Host"
              value: "{{ source_ip }}"  # Substitua pelo IP de origem
          destinationNetworks:
            - type: "Host"
              value: "{{ destination_ip }}"  # Substitua pela URL ou IP de destino
          sourcePorts: 
            - objectId: "{{ source_port }}"
          destinationPorts: 
            - port: "{{ destination_port }}"
              protocol: "{{ protocol }}"