---
- name: Configurar regra de firewall 1:1 no Cisco Firepower
  hosts: all
  connection: local
  gather_facts: no
  collections:
    - community.network

  tasks:

    - name: Configurar a regra de acesso correspondente
      ftd_configuration:
        operation: "upsertAccessRule"
        path_params:
          parentId: "default"
        query_params: {}
        data:
          name: "{{ nat_rule_name }}"
          ruleAction: PERMIT
          eventLogAction: LOG_BOTH
          enabled: true
          type: accessrule
          sourceZone: "outside_zone"
          destinationZone: "inside_zone"
          sourceNetworks:
            - type: "host"
              value: "{{ source_ip }}"  # Substitua pelo IP de origem
          destinationNetworks: 
            - type: "host"
              value: "{{ destination_ip }}"  # Substitua pela URL ou IP de destino
          sourcePorts: "{{ source_port }}"
          destinationPorts: 
            - port: "{{ destination_port }}"
              protocol: "{{ protocol }}"